from pathlib import Path
from datetime import datetime, timezone
import hashlib,json
OUT=Path(__file__).parent;TMP=OUT.parent;INTAKE=TMP/'trifusion_supported_balance_q1_complete_20260921'
def js(p):return json.loads(p.read_bytes())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(name,x):(OUT/name).write_text(json.dumps(x,indent=2)+'\n',encoding='utf-8')
t=js(OUT/'independent_text_replay.json');a=js(OUT/'remote_arrays_attempt2.json');b=js(OUT/'remote_bindings.json');c=js(OUT/'claims_cost_replay.json');inputs=js(OUT/'input_manifest.json')
assert all(x['status'].startswith('PASS') for x in (t,a,b,c))
assert t['scientific_status']=='Q1_FAIL' and not t['next_phase_qualified']
failures=[
 dict(id='AF01',class_='auditor_runtime',status='FAILED_ATTEMPT_PRESERVED',check='Default python executable usable',observed='No pyvenv.cfg file',resolution='Used existing uv cached numpy/paramiko environment; no environment installed.'),
 dict(id='AF02',class_='auditor_path',status='FAILED_ATTEMPT_PRESERVED',check='Initial snapshot path trifusion/signal_preserving_v8.py',observed='Path assertion failed; actual file is modeling/trifusion/signal_preserving_v8.py',script='prepare_local_attempt1.py',resolution='Corrected to actual repository path; partial snapshots were verified byte-identical before continuing.'),
 dict(id='AF03',class_='auditor_assumption',status='FAILED_ASSUMPTION_REPLACED_WITH_EVIDENCE',check='Q1 observed project_commit equals pipeline launch code_commit',observed=dict(q1=b['q1_observed_commit'],pipeline=b['pipeline_commit']),script='replay_text_attempt1.py',resolution='Preserved both commit fields; all98 bound repository paths matched both Git blobs and current remote bytes. No source identity inferred from a mutable publication HEAD.'),
 dict(id='AF04',class_='actual_evidence_limit',status='FAIL_BITWISE_WARMUP_EQUIVALENCE',check='Both endpoints have bitwise-identical warmup trajectories',observed=t['paired_warmup'],script='replay_text_attempt2.py',resolution='Removed unsupported equality claim. Input records/pixels and initialization match; original arithmetic branch is preserved in each run, but exact paired trajectories are not established.'),
 dict(id='AF05',class_='auditor_shape',status='FAILED_ATTEMPT_PRESERVED',check='Assumed full role output width1536',observed='remote_arrays_attempt1.json.stderr: line61 shape assertion',script='remote_arrays_attempt1.py',resolution='Corrected to source-declared4608D (3072D Signal prefix plus1536D role). Second complete remote audit passed; original experiment unmodified.'),
 dict(id='PF01',class_='original_experiment_verifier',status='FAIL_PRESERVED',check='Original Q1 CPU scalar exact ratio',evidence=str(INTAKE/'q1_cpu.log'),observed='math.sqrt controller versus **.5 verifier differs at6 supported role records on remote Python3.10.14',resolution='Original pipeline remains STOPPED_AT_Q1_CPU; separate hash-guarded posthoc replay uses actual sqrt operation.'),
 dict(id='PF02',class_='posthoc_failed_attempt',status='FAIL_PRESERVED',check='First sqrt repair execution-source binding',evidence=str(INTAKE/'q1_cpu_sqrt_recheck/verification.log'),observed='AssertionError: tools/verify_msvr_supported_gradient_balance_stats.py',resolution='Current bound source is restored to exact original bytes. Never characterize all historical posthoc source states as unchanged.'),
 dict(id='PF03',class_='posthoc_failed_attempt',status='FAIL_PRESERVED',check='Bound sqrt-only weighted-norm formula',evidence=str(INTAKE/'q1_cpu_bound_sqrt_recheck/verification.log'),observed=t['original_formula_failures'],resolution='Separate final replay converts only formula coefficients to IEEE FP32; original1e-7 threshold retained. All1743 balanced supported role combinations pass.'),
 dict(id='PF04',class_='sealed_r1_engineering',status='FAIL_RETAINED_NOT_RERUN',check='R1 auxiliary subtraction-reference error',observed='0.006824872357540746 >0.005 at fold0 control step4;3 completed updates; noQ1',evidence='snapshots/repo/refine-logs/msvr310_supported_gradient_balance_v1/EXPERIMENT_PLAN.md:100',resolution='R2 direct auxiliary is separately registered. This audit does not relabel or rerun R1.'),
 dict(id='SF01',class_='scientific',status='FAIL',check='Registered paired and Signal gate groups',observed=dict(paired=t['paired_gates'],signal=t['ranking']['balanced']['gates']),resolution='Q1_FAIL; no threshold changes or promotion.')]
save('failed_checks.json',failures)
limits=[
 'One MSVR310 internal source-OOF study, seed42, three identity folds and two fixed endpoints. Folds and roles are not independent training seeds.',
 'The same internal protocol informed previous method development. Identity bootstrap describes fixed predictions and query clusters, not seed variance, training uncertainty or adaptive method selection; this is not untouched external or official-test evidence.',
 'No original training forward, per-step parameter-gradient vector or AdamW moment/scaler trajectory was regenerated. Saved norm/cosine/RNG/buffer/head/reencoding flags remain runtime witnesses. Q1 direct-reference checks are zero; prior M0 witnesses are engineering-only.',
 'Cumulative203/203 nonzero tensors is a union over each run; it is not evidence of every tensor having nonzero gradient at every step.',
 'Both endpoints share scalar objective definitions, initialization and source inputs, but warmup numeric trajectories already differ at step2. Supported candidate uses separate direct R/A arithmetic; control uses combined backward. The tiny measured delta is not a bitwise-isolated coefficient-only causal estimate.',
 'The13 auxiliary scalar terms and their weighted total were verified as saved ledgers. Per-step logits and residual feature tensors are not retained, so those13 losses cannot each be freshly reconstructed from model outputs.',
 'Final checkpoints, frozen subsets and feature-derived distances were independently reconstructed on CPU; images and model forwards were not re-read/re-executed. Current image-path existence and filename labels were checked, not image semantic annotation quality.',
 'The original pipeline failed and was not rewritten. Final completion is a separate disclosed posthoc arithmetic receipt. A prior failed repair changed the stats-file binding; current original bytes are restored and verified.',
 'Review is fresh same-family/provisional; requested gpt-6-astra/max routing is not backend attestation. All large tensors remain remote.'
]
checks={
 'A_ground_truth':dict(status='PASS',details='Dataset TRAIN identities/scenes parsed from all1032 filenames; full-path fold isolation through B0 checkpoint, role initialization, all1950 B0 step memberships and all1560 Q1 steps; all95 single-scene distractor IDs retained.',evidence=['latest_claims/tools/build_msvr310_train_oof_protocol.py:12-55','snapshots/repo/tools/train_msvr310_signal_oof.py:68-99','snapshots/repo/tools/train_msvr310_trifusion_oof.py:27-55','remote_arrays_readonly.py:25-49','replay_text_independent.py:61-113','snapshots/remote_text/root/autodl-tmp/trifusion-v2/comparators/Signal-cd1b0a6/utils/metrics.py:48-69']),
 'B_score_normalization':dict(status='PASS',details='Raw per-query AP/CMC with true positive-count denominator; pooled queries, standard unit-feature distances. No prediction-max/mean performance normalization. EMA norm ratios are optimizer coefficients, not retrieval metrics.',evidence=['snapshots/repo/tools/msvr_cross_scene_smooth_ap.py:30-54','snapshots/repo/tools/train_msvr310_trifusion_oof.py:196-241','snapshots/repo/tools/msvr_supported_gradient_balance.py:23-43','replay_text_independent.py:34-40']),
 'C_results_and_provenance':dict(status='PASS_WITH_DISCLOSED_REPAIR',details='All43 intake files,159 remote binding rows,98 source Git-blob comparisons and43 final verifier file references matched. All terminal values agree. Original failed pipeline and three failed CPU attempts remain visible; latest tracker accurately records CPU completion/audit pending.',evidence=['input_manifest.json','remote_bindings.json:1','claims_cost_replay.json','ranking_reader.diff','snapshots/repo/tools/recheck_msvr_supported_balance_sqrt.py:11-31','failed_checks.json']),
 'D_live_call_paths':dict(status='PASS_WITH_RUNTIME_LIMITS',details='Current loss and candidate leaf derivatives, historical VJP, complete role R/A, head preservation, single unscale/AdamW step, final evaluation and actual metric outputs are connected. All saved objective/controller states checked. Q1 intentionally lacks direct-reference vector regeneration.',evidence=['snapshots/repo/tools/train_msvr_supported_gradient_balance.py:119-184','snapshots/repo/tools/train_msvr_supported_gradient_balance.py:222-320','snapshots/repo/tools/train_msvr_supported_gradient_balance.py:383-449','snapshots/repo/tools/msvr_supported_gradient_balance.py:65-96','snapshots/repo/tools/probe_msvr_role_set_gradients.py:29-50','remote_arrays_attempt2.json:1']),
 'E_scope':dict(status='WARN',details='600 unique legal queries/60 query IDs;1032 complete fold-local galleries/155IDs including95 distractor IDs;3folds×2endpoints×5outputs, seed42 only. All120epochs retained as training data. No statistical or causal superiority, general robustness, independent-seed or official-test claim.',evidence=['independent_text_replay.json','claims_cost_replay.json','latest_claims/results/MSVR310_SUPPORTED_GRADIENT_BALANCE_R2_Q1_2026-09-21.md:3-35','snapshots/repo/refine-logs/msvr310_supported_gradient_balance_v1/EXPERIMENT_PLAN.md:7-13']),
 'F_evaluation_type':dict(status='PASS',main='real_gt',details='Terminal retrieval uses dataset identities/scenes. T0 mathematical fixtures are simulation_only. Norm/controller/direct-reference/overfit checks are engineering proxies, never substituted for retrieval GT.',evidence=['snapshots/repo/tools/check_msvr_supported_gradient_balance_math.py:12-133','snapshots/repo/tools/train_msvr_supported_gradient_balance.py:185-216','snapshots/repo/tools/train_msvr310_trifusion_oof.py:196-241'])
}
claims=[dict(id='negative_fixed_study',impact='supported',text='Registered R2 completes but fails both five-gate groups; seal this exact study.'),dict(id='controller_operation',impact='supported_with_limits',text='All supported/unsupported/warmup scalar states and weights conform to contract; actual gradients are historical witnesses.'),dict(id='causal_retrieval_superiority',impact='unsupported',text='Tiny paired gain, negative identity-bootstrap lower bound, negative fold/Transformer gain and paired warmup drift preclude superiority and bitwise-isolated causal attribution.'),dict(id='source_objective',impact='supported_descriptive_only',text='Last65 cross-scene losses decrease in each fold while both hard diagnostics increase; this does not identify AdamW task shares or retrieval mechanism.'),dict(id='official_or_whole_goal',impact='unsupported',text='No official-test result, general success, multi-seed robustness or whole-goal completion.'),dict(id='never_changed_source',impact='needs_qualifier',text='Final source bytes match both execution commits; first repair failed the stats source binding. State restored/current exactness, not never modified in any posthoc attempt.')]
hashes={r['remote']:'sha256:'+r['sha256'] for r in inputs['local_intake']}
hashes.update({r['source']:'sha256:'+r['sha256'] for r in inputs['snapshots']})
hashes.update({r['path']:'sha256:'+r['sha256'] for r in b['bindings']})
hashes.update({r['path']:'sha256:'+r['sha256'] for r in b['verified_files']})
report=dict(audit_skill='experiment-audit',verdict='WARN',overall_verdict='warn',integrity_status='warn',closure='CLOSED_WITH_LIMITS',deterministic_checks_status='pass',engineering_status='PASS_COMPLETE_SAVED_EVIDENCE',scientific_status='Q1_FAIL',next_phase_qualified=False,reason_code='complete_deterministic_replay_with_runtime_causal_scope_limits',summary='All complete saved Q1 arithmetic, source isolation, current hashes, terminal checkpoints and raw rankings pass independent checks. Scientific gates fail; limits remain on training-vector reconstruction, causal isolation and scope.',date='2026-09-21',generated_at=datetime.now(timezone.utc).isoformat(),agent_id='/root/audit_supported_gradient_balance_q1_20260921',verdict_id='supported_balance_q1_20260921_independent',executor_model='Codex, backend unattested',executor_family='openai',reviewer_model='gpt-6-astra requested; backend unattested',reviewer_reasoning='max requested; backend unattested',reviewer_family='openai',requested_fork='none',review_independence='same-family',acceptance_status='provisional',backend_attestation='unavailable',trace_path=str(OUT),request_path='C:/Users/gb/.trifusion_github_publish_22c3bee/.aris/traces/experiment-audit/2026-09-21_supported_balance_q1/001-audit-request.md',audited_input_hashes=hashes,checks=checks,claims=claims,limitations=limits,remaining_engineering_audit_blockers=[],action_items=['Publish this complete audit with WARN/CLOSED_WITH_LIMITS and scientific Q1_FAIL, replacing audit-pending status only.','Retain original stopped pipeline, all failed repair attempts and the distinct final posthoc receipt.','Qualify never-unchanged wording as current/restored hash equality; preserve warmup and separate-backward numerical differences.','Do not promote or tune this failed fixed version; no official-test, seed/epoch/gate scan or rescue is supported by this audit.'],verification_scope=dict(training_steps=1560,role_steps=4680,epochs=120,source_distance_elements=116501504,retrieval_distance_rank_elements=2069520,query_endpoint_output_rows=6000,paired_identity_output_rows=300,final_role_checkpoints=6,source_baseline_checkpoints=3,source_baseline_steps=1950,coefficient_conversion_checks=9360,model_forwards=0,optimizer_updates=0,official_image_reads=0,binary_downloads=0,per_step_gradient_regeneration=False),original_pipeline_status='STOPPED_AT_Q1_CPU',posthoc_verification_path=str(INTAKE/'q1_cpu_arithmetic_recheck/verification.json'),summary_sha256=sha(INTAKE/'q1/summary.json'),cpu_receipt_sha256=sha(INTAKE/'q1_cpu_arithmetic_recheck/verification.json'),pipeline_commit=b['pipeline_commit'],q1_observed_commit=b['q1_observed_commit'],git_bound_source_paths=98,results=t['ranking'],paired_gains=t['paired_gains'],paired_fold_gains=t['paired_fold_gains'],paired_bootstrap_lower=t['paired_bootstrap_lower'],paired_gates=t['paired_gates'],failure_ledger='failed_checks.json')
save('EXPERIMENT_AUDIT.json',report)
metric_table='\n'.join(f"| {o} | {t['ranking']['control']['metrics'][o]['mAP']:.9f} | {t['ranking']['balanced']['metrics'][o]['mAP']:.9f} | {t['paired_gains'][o]:+.9f} | {t['ranking']['control']['metrics'][o]['Rank-1']:.6f} | {t['ranking']['balanced']['metrics'][o]['Rank-1']:.6f} |" for o in ('baseline_only','fused','cnn','transformer','mamba'))
scope_table='\n'.join(f"| {r['fold']} | {r['source_ids']} | {r['heldout_ids']} | {r['gallery']} | {r['queries']} | {r['distractor_ids']} / {r['distractor_records']} |" for r in t['fold_scope'])
cost_table='\n'.join(f"| {name} | {v['epoch_seconds']:.3f} | {v['peak_allocated_mib']:.3f} | {v['peak_reserved_mib']:.0f} | {v['fresh_role_forwards']} | {v['history_vjp_forwards']} |" for name,v in c['cost'].items() if name.startswith('fold_'))
q1bytes=sum(r['bytes'] for r in b['run_file_inventory'] if r['path'].startswith('q1/'))
md=f'''# Supported gradient balance R2 — complete independent Q1 audit

Date: 2026-09-21. **WARN / CLOSED_WITH_LIMITS**. Deterministic saved-evidence checks: **PASS**. Engineering audit blockers: **none**. Scientific qualification: **Q1_FAIL**, next phase **false**. These are separate conclusions.

Fresh delegated reviewer `/root/audit_supported_gradient_balance_q1_20260921`; requested gpt-6-astra/max/fresh-none. **Same-family / provisional; backend attestation unavailable.** No further delegation, training, optimizer update, model forward, official-test read, environment installation or binary download was performed.

The audit directory is `{OUT}`. `R` below means `snapshots/repo/`; `U` means `snapshots/remote_text/root/autodl-tmp/trifusion-v2/comparators/Signal-cd1b0a6/`; `I` means the existing byte-exact intake `{INTAKE}`. Report/source snapshots, actual scripts, raw stdout/stderr, replay tables and hashes are retained here. The original request remains at the supplied `.aris/traces/experiment-audit/2026-09-21_supported_balance_q1/001-audit-request.md`.

## A. Ground-truth provenance — PASS

Dataset identities, camera and scene fields come from the MSVR310 **official training split filenames**, not model predictions. I reparsed all1,032 modality-triplet filenames and checked all3,096 current remote source path existences. The builder's dataset-label hash and filename offsets agree with the inspected upstream loader. The runtime reads explicit protocol source/gallery record indices through `records_for`; it does not instantiate the upstream dataset class that would also enumerate official query/test sets. Source: `latest_claims/tools/build_msvr310_train_oof_protocol.py:12-55`; R `tools/train_msvr310_signal_oof.py:68-99`; U `data/datasets/msvr310.py:68-89`.

The identity-disjoint split is reconstructed from sorted cross-scene-eligible and single-scene identity groups. All155 IDs and1,032 records enter exactly one heldout fold; training for each fold uses its complement. All600 legal query records/60 query identities are included. All95 single-scene identities/432 nonquery records remain in the complete galleries as distractors:

| Fold | Source IDs | Heldout IDs | Gallery records | Legal queries | Distractor IDs / records |
|---|---:|---:|---:|---:|---:|
{scope_table}

The upstream metric function actually removes **same identity AND same scene** at U `utils/metrics.py:67-69`; its old person-ReID docstring does not define the executed rule. Every different-identity record, including same-scene negatives, remains. This rule was applied independently to every saved permutation. R `tools/train_msvr310_trifusion_oof.py:196-241` calls the imported author metric and stores agreement with its own scene scorer.

Full-path isolation was inspected through source-only B0 training, B0 checkpoint source/heldout IDs, seed42 fresh role initialization and all1,560 current/history memberships. The independent remote checker additionally read all1,950 recorded B0 training steps and verified their source memberships; the three B0 checkpoints, their final state hashes, original retrieval-array hashes and six terminal role checkpoint bindings passed. This checks existing evidence and is not a new baseline/M0/source-census run. R `tools/train_msvr310_trifusion_oof.py:27-55`; `remote_arrays_readonly.py:25-49`; `remote_arrays_attempt2.json:1`.

Image pixels and semantic annotation correctness were not freshly re-inspected. Per-step actual pixel hashes remain the original run's witnesses, but the full paired pixel-hash sequences match.

## B. Score normalization — PASS

Terminal mAP is raw mean query AP multiplied by100; AP uses precision at the real labeled positive positions divided by that query's labeled positive count. Rank-1/5/10 are raw fractions. Results pool all queries **after fold-local ranking**, without cross-fold distances or averaging fold mAPs equally. Unit feature normalization and squared Euclidean distances are the registered metric geometry, not rescaling by the model's own best output. No suspicious self-maximum score normalization was found.

The source loss uses `score=1-d²/2`, sigmoid temperature0.01, current-anchor positives from same-ID/different-scene pairs, and the **mean of eligible anchors only**. Same-ID/same-scene candidates including self are ignored, not made negative. The positive item being ranked is excluded from its own comparison and contributes the explicit rank-one offset. Missing-positive anchors retain their other supervision and remain candidates for other anchors. Zero-eligible batches return graph-connected zero for fused ranking. R `tools/msvr_cross_scene_smooth_ap.py:11-54`.

Every saved source fused distance was used to independently recompute standard Smooth-AP, cross-scene AP and hard diagnostics; all four stored spaces were shape/finite/nonnegative checked. Maximum per-anchor cross-scene difference is **{max(r['max_cross_ap_error'] for r in a['endpoints']):.12g}**, below the unchanged2e-6 bound. Largest reconstructed scalar objective difference is **{max(r['max_objective_error'] for r in a['endpoints']):.12g}**. The13 other scalar terms and weighted total passed ledger checks, but absent logits/residual features prevent fresh reconstruction of each auxiliary loss. `remote_arrays_attempt2.json:1`; `replay_text_independent.py:118-125`.

EMA norm ratios, coefficient bounds, relative-gradient errors and actual AdamW parameter deltas are engineering quantities. They are not performance scores or task-specific update shares.

## C. Result existence, values and provenance — PASS with disclosed repairs

- All43 byte-exact intake files match their inventory. All43 files referenced by the terminal CPU receipt were freshly rehashed remotely, including saved arrays and six checkpoints.
- The remote binding traversal checked159 rows. All98 distinct bound repository paths match both pipeline execution commit `{b['pipeline_commit']}` and Q1's observed publication commit `{b['q1_observed_commit']}`. The mutable publication HEAD is not used as a substitute for these bindings. Five local files use CRLF bytes and therefore differ from frozen remote hashes; the remote LF bytes and both execution Git blobs pass. Raw local bytes are separately retained in the manifest.
- Config SHA256 `9ce36299299efbc09ccfb72f5b1c4fed20fc1026bd9fee1bd55a591d6950ec7b`; summary SHA256 `{report['summary_sha256']}`; final posthoc CPU receipt SHA256 `{report['cpu_receipt_sha256']}`.
- Original `pipeline.json` remains **STOPPED_AT_Q1_CPU**, with original CPU exit1 and preserved `q1_cpu.log`; no original `q1_cpu.json` was fabricated. Final completion is `q1_cpu_arithmetic_recheck/verification.json` plus actual exit0 `receipt.json`.

The failure chain is preserved: (1) original exact sqrt/power mismatch; (2) first repair failed the stats source hash; (3) hash-bound sqrt-only repair failed one weighted-norm identity. The final hash-guarded in-memory transformation changes only the sqrt operation to the executed `math.sqrt` and converts the weighted-norm formula's scalar coefficients to actual float32 representation. Threshold1e-7, exact state comparisons, M0 reference limits0.005/1e-8 and all scientific gates stay unchanged. R `tools/recheck_msvr_supported_balance_sqrt.py:11-31`; R `tools/verify_msvr_supported_gradient_balance_stats.py:7-9,60-77`; I repair logs; `failed_checks.json`.

On the actual remote Python3.10.14 runtime, six supported role records differ between sqrt and exponentiation by one binary64 ULP; all recorded values match sqrt. Local Python3.13 yields five such differences, so that platform-specific count is explicitly separated. The independently reproduced weighted-norm failure is fold0/balanced/step71/Mamba:5.4609169631e-7 original error versus5.0530124677e-7 threshold. Correct FP32 coefficients give4.6714214719e-9 error. All1,743 supported balanced role combinations pass the unchanged formula threshold after representation alignment. All9,360 applied coefficient conversions were checked using the installed CPU PyTorch2.5.1; CUDA remained uninitialized. This is arithmetic verification, not GPU gradient regeneration.

**Wording qualifier:** the first failed repair's source-binding assertion means the stats file was not byte-identical at that point. Current restored source bytes are exact and the final replay verifies them. The phrase “original execution files unchanged” must describe the preserved/restored final bound bytes, not claim that no verifier file was ever temporarily changed during posthoc work. Nothing here indicates training or checkpoint mutation from that failed CPU attempt.

The latest result table, all1,560 exported steps,120 epochs and4,680 role rows were checked against primary logs. Report numbers, late-source comparisons, query changes and coefficients match. The original ranking reader's repaired variant changes only terminal provenance handling; ranking/gate/bootstrap computation is unchanged (`ranking_reader.diff`). The latest tracker accurately records completed Q1/CPU and audit in progress; replacing that pending label with this audit is a publication action, not an unfinished computation.

## D. Executed paths and full runtime scope — PASS with limits

The actual trainer calls cross-scene objectives, replaces only `triplet_fused` after65 warmup steps, differentiates the current ranking objective and direct auxiliary sum, executes the original combined backward, then restores all historical ranking derivatives by grouped VJP. Only current records are anchors; historical records are candidates, **zero historical anchors**. The complete ranking vector is current plus history before role statistics and weighting. R `tools/train_msvr_supported_gradient_balance.py:119-184,222-268`.

Historical entries are unique by record index with newest exposure winning; current indices are excluded, maximum age8, capacity512. Frozen stored fields are re-encoded under current role parameters using the original encoder-entry RNG. RNG forks and buffer comparisons surround replay; zero upstream groups are skipped by the existing rule. R `tools/msvr_instance_memory.py:15-37`; R `tools/msvr_freshness_probe.py:48-60`; R `tools/probe_msvr_role_set_gradients.py:29-50`; R `tools/probe_msvr_history_candidate_gradients.py:43-50`; R trainer `228-249`.

Whole-role grouping covers42 CNN,54 Transformer and93 Mamba encoder tensors,189 total, disjoint and complete. The14 neck/classifier trainable tensors keep original current-total gradients. Supported balanced steps apply `wR*(Rcurrent+Rhistory)+wA*A_direct`; control/warmup/unsupported preserve original `current_total+Rhistory`. The controller uses EMA0.9, square-root ratio clipped0.25..4, epsilon1e-12 and weights totaling2 within0.4..1.6. All4,680 before/after states, support identities/relations, ratios, proposed/applied weights and scalar vector identities were independently checked. R `tools/msvr_supported_gradient_balance.py:10-43,65-106`; R trainer `267-320`.

Actual Q1 coverage is390 warmup steps,1,162 supported postwarmup steps and8 unsupported postwarmup steps. The latter occur in **both** arms at fold0 step180, fold1 step221, fold2 steps133/232. EMA remains unchanged, weights are1/1 and complete ranking norms are zero; the other supervision and optimizer updates continue. Ten additional warmup batches lack cross-scene positives but use the registered hard Triplet warmup, making18 zero-eligible batches across all phases. This extends actual branch coverage beyond M0, whose unsupported steps were absent.

Exactly one scaler unscale, finite check, AdamW step and scaler update occurs per step. No overflow was recorded. Seed42, fixed20 epochs/260 updates per endpoint, source-only initialization and M0 binding are verified. Role weights are freshly initialized and are not continued from M0 or an earlier final checkpoint. Retrieval is executed once after the fixed final reload; there is no per-epoch heldout selection. R trainer `290-346,358-449`.

All six final state hashes and frozen subsets were independently reconstructed from compact role states plus original B0 aliases. All30 saved feature spaces produce the exact stored float32 distances and full ranking permutations; an additional float64 distance calculation also agrees within2e-6. The independent CPU pass took **{a['elapsed_seconds']:.6f}s**, zero forwards/updates, CUDA uninitialized. Strict original reload-forward output parity is a historical runtime witness, not repeated here.

The cumulative203/203 nonzero-gradient record is the union accumulated at trainer `291-294`; it does **not** establish every-tensor/every-step nonzero gradients. Q1 has **zero independent direct-reference vector checks**. The earlier M0's six capacity reference positions and90 role-component comparisons retain their narrow engineering scope; no M0 rerun was made. Original per-step vectors, logits and AdamW moment/scaler states are unavailable, so scalar identities cannot prove coordinate-wise derivatives or regenerate parameter update attribution.

Both arms have the same scalar objective definitions, but that scalar total is not a single globally weighted candidate objective: role-specific gradient coefficients generally cannot be represented by one common scalar weight. Finite-precision direct-sum versus combined-backward discrepancy is nonzero, and the original R1 subtraction failure remains failed. Supported direct-sum relative differences have medians0.000705..0.001028 and maximum0.001516 across the logged role/fold/endpoint summaries; these are diagnostics, not relaxed reference gates (`claims_cost_replay.json`).

Paired records/pixels and initialization match, but all three folds first differ in warmup scalar trajectories at step2. Maximum total-loss differences are0.0011240244/0.0014045238/0.0017092228. The balance controller is inactive then. This observation prevents a bitwise-isolated coefficient-only causal claim; its underlying runtime source was not independently localized. It is not evidence that source samples or checkpoint selection differed.

## E. Scope, outcomes and scientific gates — WARN / Q1_FAIL

This is one repeatedly developed **internal MSVR310 identity-OOF protocol**, seed42, three folds and two endpoints. Folds and role blocks are not independent training seeds. All600 queries/60 query IDs and complete galleries are covered, with6,000 query×endpoint×output rows,300 paired identity×output rows,120 real training epochs and4,680 role-step records retained.

| Output | Control mAP | Balanced mAP | Paired delta pp | Control R1 | Balanced R1 |
|---|---:|---:|---:|---:|---:|
{metric_table}

Fused paired fold gains are **+0.129966707 / -0.107213849 / +0.146774279pp**. Paired identity-bootstrap lower bound is **-0.126141312pp**. The original paired gates are fail/fail/fail/fail/pass: gain≥1pp fails, all-fold nonnegative fails, all-role nonnegative fails (Transformer), bootstrap lower>0 fails, candidate fused strictly best passes.

Balanced versus fixed Signal gains fused+0.323268810pp, with fold gains+4.233440447/-3.163518323/-0.219742706; CNN/Transformer/Mamba are below Signal. Its bootstrap lower is **-1.817469561pp** and the Signal group also passes only1/5. Both complete gate groups are required, hence scientific **Q1_FAIL**.

Bootstrap independently reproduces the registered10,000 draws/seed42/linear2.5th percentile: sample60 identity clusters with replacement and divide summed AP differences by sampled query counts. It is not a macro identity average, seed-variance analysis or protection against repeated method development on these folds. Full raw negative results remain. Fused has240 AP improvements,203 declines,157 ties; Rank-1 repairs3 and new errors2.

Last65 cross-scene objective means decrease in each fold; batch-hard and expanded-hard diagnostics increase in each fold. The aggregate values and all late epochs match the report. This supports a descriptive source-objective observation, not an AdamW-causality claim or generalization mechanism. No heldout epoch scores were invented.

## Actual resource and storage accounting

| Endpoint | Fit epoch seconds | Peak allocated MiB | Peak reserved MiB | Fresh role forwards | History VJP record forwards |
|---|---:|---:|---:|---:|---:|
{cost_table}

Q1 wall time is15,576.741760s (4.326873h); summed recorded fit epochs are15,445.481150s. Each arm performs780 current-rank and780 direct-auxiliary extra backward calls,292,800 fresh role-record forwards and290,560 historical-VJP record forwards. Thus both arms bear the same measured extra-call counts; equal counts do not imply bitwise trajectories or equal elapsed time. No extra direct-reference forward is made in Q1. There are9,080 historical VJP groups total and585,600 fresh role-record forwards including the six64-record zero-reencoding checks.

Current training exposures total99,840, plus355,244 repeated historical candidate exposures and1,032 unique official-training records in the protocol. Source records exposed per fold are672/683/709, repeated in both arms; exposure counts are not independent samples. Original source Signal prerequisite1950 updates, R2 M0248 updates and archived R1's3 completed updates are separate prior costs, not included as Q1 updates or treated as budget-matched free initialization.

The remotely inventoried whole run occupies **{b['storage_total_bytes']:,} bytes**, of which Q1 subdirectory files occupy **{q1bytes:,} bytes**. This includes retained evidence; no model/array/image was downloaded. No new inference parameter is introduced, but training derivatives, historical replay, logs and distance storage have real cost.

## F. Evaluation classification — PASS

Main terminal retrieval: **real_gt**, internal train-split identity-OOF. Source label/mask/loss computation also uses dataset labels. T0 synthetic differentiation and scalar fixtures: **simulation_only**, not performance. Direct derivative/RNG/buffer/head/overfit/coefficients: engineering proxies or saved runtime witnesses. No synthetic proxy was substituted for dataset retrieval GT.

## Claim impact and closure

The latest negative-result report is numerically supported. Its completeness claim applies to saved terminal arithmetic and covered records. Superiority, robust unknown-identity transfer beyond this internal protocol, independent multi-seed support, bitwise coefficient-only causality, task-specific AdamW fractions, official performance and whole-goal success are unsupported.

**No remaining engineering or audit computation blocker.** Publish this WARN/CLOSED_WITH_LIMITS audit and retain Q1_FAIL. Replace audit-pending documentation only after attaching the audit; qualify restored source wording as above. Preserve all original failures and current code/config/checkpoint hashes. Do not alter gates, select another epoch, retrain or rescue this failed fixed version on these results. No further experiment was launched or authorized by this audit.

The auditor's own failed attempts and false assumptions are explicit in `failed_checks.json`: default Python runtime failure, one mistaken snapshot path, mutable commit equality assumption, false warmup bitwise equality, and mistaken full-branch width. Scripts, original assertions and remote stderr remain. Corrected audit scripts used source-declared paths/widths and current evidence; no experimental tolerance or gate was changed.

Primary new outputs: `EXPERIMENT_AUDIT.json`, `independent_text_replay.json`, `remote_bindings.json`, `remote_arrays_attempt2.json`, `claims_cost_replay.json`, `all6000_query_endpoint_output_rows.csv`, `all300_identity_output_deltas.csv`, `all4680_gradient_role_rows.csv`, `all120_training_epochs.csv`, `failed_checks.json`, `final_response.md`. `artifact_manifest.json` hashes all final audit artifacts, and `input_manifest.json` plus report `audited_input_hashes` bind supplied inputs. Large arrays/checkpoints remain remote.
'''
(OUT/'EXPERIMENT_AUDIT.md').write_text(md,encoding='utf-8')
print(json.dumps(dict(status='AUDIT_REPORTS_WRITTEN',verdict='WARN',closure='CLOSED_WITH_LIMITS',scientific_status='Q1_FAIL',output=str(OUT))))
